---
title: "Composition-climate paper"
author: "Simon Goring *et al*."
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
pdf_document:
pandoc_args: "-H margins.sty"
bibliography: composition.bib
csl: harvard1.csl
---


Land use patterns and historical contingency change climate optima for key forest genera in the Northeastern United States.
========================================================

*Historic land use and forest change over the centuries since Euroamerican settlement have significantly changed the structure and composition of forests in the upper Midwestern United States.  The extent to which this change has affected the realized climate niche for key taxa is less well known.*

*Predictions for future species range shifts are predicated largely on correlative models that relate modern species distributions to climate parameters in the modern era.  Given the extent of regional forest change and recent losses to key forest taxa including Hemlock, Elm and Chestnut it is possible that certain taxa have shiften with respect to climate change over the last century.  The additional pressure of climatically biased land use conversion for agriculture along the western and southern border of the upper Midwest means that the shift in climate space may be most pressing in a region of climate space that is critically important for understanding future species responses to climate change.*

```{r, fig.width=5}
# Load climate data and generate the pre-sett and modern bounds:
#  Pre-settlement climate: 1900 - 1930
#  Modern climate: 1960 - 1990

source('R/Setup_R.R')
source('R/load_climate.R') # gives then.clim & now.clim
source('R/load_fia.R')     # gives agg.dens
source('R/load_ncdf.R')    # gives western and eastern

```

Introduction
==============

Over the past 200 years centennial scale climate variability and land use change have interacted to transform the forests of the northeastern United States. There are clear indications that modern forests, as represented by the Forest and Inventory Analysis show greater homogeneity and significantly different species associations than pre-settlement forests [@goring2015preset]. This shift has occured over a period during which climate has begun to show the effects of anthropogenic warming, and a period in which we have increasingly used the relationship between modern tree species distributions and climate to understand future responses of tree species and forest assemblages to climate change.

If modern species distributions have been affected by land use change in a random fashion then we should expect little effect on the resulting predictions.  In the midwestern United States we see a strong gradient of temperature and precipitation that results in two major ecotones, one from prairie and savanna to closed forest, in an approixmately west to east direction, and from conifer dominated, sub-boreal forests to decidious forest in a north to south direction.  Goring et al [@goring2015preset] have shown that land use change has significantly changed the strength and structure of this ecotone, but did not examine how these shifts might affect the relationships between climate and distribution for individual taxa.

We use gridded climate data products and estimates of pre-settlement vegetation to develop climate-vegetation relationships for X major tree taxa in the upper Midwestern United States to understand how climate and land use change have interacted since Euro-American settlement to affect species distributions in the region, and to examine the possible implications of these shifts to future estimates of species resillience to climate change across the region.

Methods
===============
We pair pre-settlement vegetation data from the Public Land Survey System aggregated to a 64km^2^ grid [@goring2015] with annually resolved climate data for the region.  PLSS vegetation data contains no uncertainty, however it is spatially discontinuous, particularly in the south where digitization of PLSS records has occured at a slower rate.  Additionally, data in the northeastern United States [@thompson2013four] from town Proprietor Surveys is recorded arially, with no variance within township polygons.  To accomodate these different data sources a conditional autoregressive model was applied to the data, providing the ability to obtain uncertainty estimates across the domain [@paciorek2015comp].

The analysis follows a blocked sampling method.  We generate probability density functions for actual PLSS presence, by taxon, at the settlement era and for the same PLSS space in the modern era.  We also generate climate data for the FIA presence, and we generate climate space for modern land use.  In this way we can test how much of the change in shape is the result of changing land use vs changing climate since the early part of the century.

We also develop estimates of the modern climate space that taxa would occupy if they remained in place, with only climate changing, and vice versa (need better explanation here).

Results
---------------

Discussion
----------------

Figures
--------------

References
---------------